
app = "dan-edwards-developer-next"
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "3000"

[[restart]]
  policy = "on-failure"
  retries = 2
  processes = ["app"]
